apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
# Uncomment to include Apicurio Registry:
# components:
#   - ../../components/apicurio
patches:
  - path: patches/httproute-hostname.yaml
  - path: patches/deployment-image.yaml
