apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - managed-cluster-set-binding.yaml
  - placement.yaml
  - placement-binding.yaml
  - placement-binding-operators.yaml
  - policy-spoke-operators.yaml
  - policy-spoke-config.yaml
  - dashboard.yaml
