apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: incident-api-spoke-placement
  namespace: incident-api-policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - blue
                - aws-ai
