FROM registry.access.redhat.com/ubi9/nodejs-22-minimal:latest

COPY package*.json ./
RUN npm ci --omit=dev

COPY server.js .
COPY lib/ lib/
COPY public/ public/

EXPOSE 4000

CMD ["node", "server.js"]
