# Red Hat build of Apicurio Registry 3.1
# Docs: https://docs.redhat.com/en/documentation/red_hat_build_of_apicurio_registry/3.1/html-single/installing_and_deploying_apicurio_registry_on_openshift/index
---
apiVersion: v1
kind: Namespace
metadata:
  name: apicurio-registry
  labels:
    app.kubernetes.io/part-of: incident-api-demo
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: apicurio-registry
  namespace: apicurio-registry
spec:
  targetNamespaces:
    - apicurio-registry
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: apicurio-registry
  namespace: apicurio-registry
spec:
  channel: "2.x"
  name: apicurio-registry
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
