apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: incident-api-auth
  namespace: incident-api
  labels:
    app.kubernetes.io/part-of: incident-api-demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: incident-api-route
  when:
    - predicate: "request.path != '/healthz'"
  rules:
    authentication:
      api-key:
        apiKey:
          selector:
            matchLabels:
              app.kubernetes.io/component: api-key
          allNamespaces: false
        credentials:
          customHeader:
            name: x-api-key
    response:
      success:
        headers:
          x-auth-identity:
            plain:
              expression: auth.identity.metadata.annotations["api-consumer"]
