apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: incident-api-ratelimit
  namespace: incident-api
  labels:
    app.kubernetes.io/part-of: incident-api-demo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: incident-api-gateway
  defaults:
    limits:
      global:
        rates:
          - limit: 50
            window: 10s
